### ISSUE TITLE
Add a star to Identify authentication method

### ISSUE THREAD

**Issue by sparkyrider** [nearcomponents/nft-app-frontend#106]
<img width="413" alt="Screen Shot 2022-01-04 at 9 51 49 AM" src="https://user-images.githubusercontent.com/16215564/148085992-1b1ba0be-ea1d-4ce9-ac2f-61447544d612.png">

**Comment by biswanathsahoo** [comment]
Added a star mark with title as "Authentication Method" on hover.
If phone number is there, then phone number is the authentication method else email id.
