### ISSUE TITLE
Didn't show contacts before

### ISSUE THREAD

**Issue by sparkyrider** [nearcomponents/nft-app-frontend#129]
<img width="802" alt="Screen Shot 2022-01-05 at 4 38 42 PM" src="https://user-images.githubusercontent.com/16215564/148299639-bd5c8bf2-8a60-4621-93e3-d2dc1cbe9d40.png">

**Comment by hvats555** [comment]
if no contacts are imported, a contact import dialogue is displayed, instead of the contact list. Contact list appears after a successful import.
