### ISSUE TITLE
Dipesh Test Ticket

### ISSUE THREAD

**Issue by sparkyrider** [nearcomponents/nft-app-frontend#139]
Test ticket info here.

**Comment by sparkyrider** [comment]
Add comments to explain what you did to fix it

**Comment by sparkyrider** [comment]
When you commit, tag your Issue (In this case #139 ) to the commit

**Comment by Dipeshwagle** [comment]
@sparkyrider Tag the issue in the PR right?

**Comment by sparkyrider** [comment]
@Dipeshwagle yes
