### ISSUE TITLE
Contact Screen doesn't pop up after I add my contacts. Related to #129

### ISSUE THREAD

**Issue by sparkyrider** [nearcomponents/nft-app-frontend#140]
The contact screen that shows my contacts is not popping up after I complete Google auth to import my contacts. 

<img width="1234" alt="Screen Shot 2022-01-06 at 1 16 41 AM" src="https://user-images.githubusercontent.com/16215564/148344046-bf093a38-cb86-4279-ade4-ff0ce9d65876.png">

**Comment by sparkyrider** [comment]
After I import my contacts, the Google Contacts screen should close and it should show the contact list screen with my contacts loaded.

**Comment by hvats555** [comment]
created pr request for the issue

**Comment by biswanathsahoo** [comment]
Fixed
