### ISSUE TITLE
Login button should be active and send you to the login screen if available otherwise sent to signup screen for now

### ISSUE THREAD

**Issue by sparkyrider** [nearcomponents/nft-app-frontend#147]

**Comment by sparkyrider** [comment]
Undo what @biswanathsahoo did here: https://github.com/nearcomponents/nft-app-frontend/commit/0c33cddd01150cc87012c1b542ecbb6a671460c4

Make the Login button link to the signup page

**Comment by Dipeshwagle** [comment]
Login function is not present yet right?

**Comment by biswanathsahoo** [comment]
Login button which is on the home page is enabled and now it's redirecting to signup page
