### ISSUE TITLE
See Contacts Immediately after Import. 

### ISSUE THREAD

**Issue by sparkyrider** [nearcomponents/nft-app-frontend#89]
<img width="762" alt="Screen Shot 2022-01-04 at 9 07 16 AM" src="https://user-images.githubusercontent.com/16215564/148079514-f567a114-bd83-4277-8c5b-6ec3eb14cc72.png">

**Comment by sparkyrider** [comment]
All contacts with email OR phone should be auto selected. The "@user" should be replaced with SMS or Email with email being the preferred output

**Comment by sparkyrider** [comment]
So when you import contacts, you should see the fullscreen contact screen with all of the contacts auto selected IF they have an EMAIL or PHONE and IF they have BOTH then show the email address. Then when the "SEND" Gift button is selected those are saved as a Var to be sent with the NFT

**Comment by hvats555** [comment]
> All contacts should be auto selected.

fixed
