### ISSUE TITLE
Make default category "Digital Art"

### ISSUE THREAD

**Issue by sparkyrider** [nearcomponents/nft-app-frontend#92]
Remove Category dropdown and hardcode default "Digital Art" category
<img width="383" alt="Screen Shot 2022-01-04 at 9 16 02 AM" src="https://user-images.githubusercontent.com/16215564/148080714-fa490236-d627-4689-957b-7166a78b3bed.png">

**Comment by hvats555** [comment]
removed dropdown and hardcoded the category as digital art

**Comment by biswanathsahoo** [comment]
@hvats555 let not remove the dropdown completely, keep the dropdown and just disable that dropdown and use css {-webkit-appearance: none; appearance: none}

**Comment by hvats555** [comment]
sure, I have disabled the dropdown menu.

**Comment by hvats555** [comment]
@biswanathsahoo added CSS to the dropdown
