### ISSUE TITLE
Hide the X

### ISSUE THREAD

**Issue by sparkyrider** [nearcomponents/nft-app-frontend#96]
Hide the "X" during the first onboarding flow. 
Might need to add a "prop" to disable the "X" on the first flow. 

<img width="1182" alt="Screen Shot 2022-01-04 at 9 22 45 AM" src="https://user-images.githubusercontent.com/16215564/148081799-4d26c3a7-dd7f-4860-964a-93f3f00b9a15.png">

**Comment by hvats555** [comment]
removed the X close button for new users to force them into the onboarding flow
